backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/media/uploads"
collections:
  - name: "projet"
    label: "Projet"
    folder: "content/projets"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["title", "weight", "commit_date"]
    summary: "{{ title }} - (date de mise à jour: {{commit_date}})"
    editor:
      preview: true
    fields:
      - label: "Titre"
        name: "title"
        widget: "string"
      - label: "Description (s'affichera dans les résultats de moteurs de recherche)"
        name: "description"
        widget: "string"
      - label: "Description détaillée"
        name: "body"
        widget: "markdown"
      - label: "Ordre d'affichage"
        name: "weight"
        widget: "number"
        required: false
      - label: "Catégorie"
        name: "categorie"
        widget: "select"
        options: ["Architecture", "Décoration"]
      - label: "Type de projet"
        name: "type_projet"
        widget: "select"
        options: ["Bureaux", "Concours", "Commerce", "Ecole", "Garage", "Habitation", "Héliport", "Médiathèque", "Restaurant"]
      - label: "Type de contrat"
        name: "type_contrat"
        widget: "select"
        options: ["Mission complète de maîtrise d'œuvre"]
      - label: "Localisation"
        name: "localisation"
        widget: "string"
      - label: "Maitre d'ouvrage"
        name: "maitre_ouvrage"
        required: false
        widget: "string"
      - label: "Budget"
        name: "budget"
        widget: "string"
      - label: "Surface"
        name: "surface"
        widget: "string"
      - label: "Année de livraison"
        name: "date_livraison"
        widget: "string"
        required: false
      - label: "Date de publication"
        name: "date"
        widget: "date"
      - label: "Images"
        name: "images"
        widget: "list"
        collapsed: false
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image, media_folder: "images", choose_url: false}
      - label: "Fiches"
        name: "fiches"
        widget: "list"
        collapsed: false
        summary: '{{fields.fiche}}'
        field: {label: Fiche, name: fiche, widget: file, media_folder: "fiches", choose_url: false}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Le Cabinet"
        name: "cabinet"
        file: "content/cabinet.md"
        fields:
          - label: "Corps de page"
            name: "body"
            widget: "markdown"
      - label: "Contact"
        name: "contact"
        file: "content/contact/_index.md"
        fields:
          - label: "Téléphone"
            name: "phone"
            widget: "string"
          - label: "Fax"
            name: "fax"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Adresse"
            name: "adresse"
            widget: "string"
          - label: "Lien Google Maps"
            name: "google_maps"
            widget: "string"
